Imports System.Data
Imports System.Data.SqlClient
Imports System.Configuration

Public Class DisplayData
    Inherits System.Web.UI.Page

    Dim connStr As String

    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        Try
            connStr = ConfigurationManager.ConnectionStrings("MyConn").ConnectionString
            If Not IsPostBack Then
                BindGrid()
            End If
        Catch ex As Exception
            Response.Write("<p style='color:red;'>Page Load Error: " & ex.Message & "</p>")
        End Try
    End Sub

    Private Sub BindGrid()
        Try
            Using conn As New SqlConnection(connStr)
                Dim cmd As New SqlCommand("SELECT * FROM USERS", conn)
                Dim da As New SqlDataAdapter(cmd)
                Dim dt As New DataTable()
                da.Fill(dt)
                GridView1.AutoGenerateEditButton = True
                GridView1.AutoGenerateDeleteButton = True
                GridView1.DataSource = dt
                GridView1.DataBind()
            End Using
        Catch ex As Exception
            Response.Write("<p style='color:red;'>BindGrid Error: " & ex.Message & "</p>")
        End Try
    End Sub

    Protected Sub GridView1_RowEditing(ByVal sender As Object, ByVal e As GridViewEditEventArgs)
        Try
            GridView1.EditIndex = e.NewEditIndex
            BindGrid()
        Catch ex As Exception
            Response.Write("<p style='color:red;'>Edit Error: " & ex.Message & "</p>")
        End Try
    End Sub

    Protected Sub GridView1_RowCancelingEdit(ByVal sender As Object, ByVal e As GridViewCancelEditEventArgs)
        Try
            GridView1.EditIndex = -1
            BindGrid()
        Catch ex As Exception
            Response.Write("<p style='color:red;'>Cancel Error: " & ex.Message & "</p>")
        End Try
    End Sub

    Protected Sub GridView1_RowUpdating(ByVal sender As Object, ByVal e As GridViewUpdateEventArgs)
        Try
            connStr = ConfigurationManager.ConnectionStrings("MyConn").ConnectionString
            Dim id As Integer = Convert.ToInt32(GridView1.DataKeys(e.RowIndex).Value)
            Dim row As GridViewRow = GridView1.Rows(e.RowIndex)
            Dim name As String = CType(row.Cells(2).Controls(0), TextBox).Text
            Dim email As String = CType(row.Cells(3).Controls(0), TextBox).Text

            Using conn As New SqlConnection(connStr)
                Dim cmd As New SqlCommand("UPDATE Users SET Name=@Name, Email=@Email WHERE Id=@Id", conn)
                cmd.Parameters.AddWithValue("@Name", name)
                cmd.Parameters.AddWithValue("@Email", email)
                cmd.Parameters.AddWithValue("@Id", id)
                conn.Open()
                cmd.ExecuteNonQuery()
            End Using

            GridView1.EditIndex = -1
            BindGrid()
        Catch ex As Exception
            Response.Write("<p style='color:red;'>Update Error: " & ex.Message & "</p>")
        End Try
    End Sub

    Protected Sub GridView1_RowDeleting(ByVal sender As Object, ByVal e As GridViewDeleteEventArgs)
        Try
            connStr = ConfigurationManager.ConnectionStrings("MyConn").ConnectionString
            Dim id As Integer = Convert.ToInt32(GridView1.DataKeys(e.RowIndex).Value)

            Using conn As New SqlConnection(connStr)
                Dim cmd As New SqlCommand("DELETE FROM Users WHERE Id=@Id", conn)
                cmd.Parameters.AddWithValue("@Id", id)
                conn.Open()
                cmd.ExecuteNonQuery()
            End Using

            BindGrid()
        Catch ex As Exception
            Response.Write("<p style='color:red;'>Delete Error: " & ex.Message & "</p>")
        End Try
    End Sub

End Class